# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from application import Application
from contact import Contact


@pytest.fixture
def app():
    fixture = Application()
    yield fixture
    fixture.destroy()


def test_add_contact(app):
    app.login(username='admin', password='secret')
    app.create_contact(Contact(firstname='test contact', mobile='+78943562435'))
    app.logout()





