# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from group import Group
from common_functions import open_home_page, login, logout


class TestAddGroup:
    def setup_method(self):
        self.wd = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self):
        self.wd.quit()

    def test_add_group(self):
        open_home_page(self.wd)
        login(self.wd, username="admin", password="secret")
        self.open_groups_page()
        self.create_group(Group(name="skdncjdns", header="kjndc skdjc ", footer="sjdcnsd kcj sdkjc sjd c"))
        self.open_groups_page()
        logout(self.wd)

    def test_add_empty_group(self):
        open_home_page(self.wd)
        login(self.wd, username="admin", password="secret")
        self.open_groups_page()
        self.create_group(Group(name="", header="", footer=""))
        self.open_groups_page()
        logout(self.wd)

    def create_group(self, group):
        # init group creation
        self.wd.find_element(By.NAME, "new").click()
        # fill in group form
        self.wd.find_element(By.NAME, "group_name").click()
        self.wd.find_element(By.NAME, "group_name").send_keys(group.name)
        self.wd.find_element(By.NAME, "group_header").send_keys(group.header)
        self.wd.find_element(By.NAME, "group_footer").send_keys(group.footer)
        # submit group creation
        self.wd.find_element(By.NAME, "submit").click()

    def open_groups_page(self):
        self.wd.find_element(By.LINK_TEXT, "groups").click()
