# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestTestaddgroup():
  def setup_method(self, method):
    self.wd = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.wd.quit()
  
  def test_test_add_group(self):
    self.open_home_page()
    self.login()
    self.open_groups_page()
    self.create_group()
    self.return_to_groups_page()
    self.logout()

  def logout(self):
    self.wd.find_element(By.LINK_TEXT, "Logout").click()

  def return_to_groups_page(self):
    self.wd.find_element(By.LINK_TEXT, "groups").click()

  def create_group(self):
    # init group creation
    self.wd.find_element(By.NAME, "new").click()
    # fill in groupform
    self.wd.find_element(By.NAME, "group_name").click()
    self.wd.find_element(By.NAME, "group_name").send_keys("skdncjdns")
    self.wd.find_element(By.NAME, "group_header").send_keys("kjndc skdjc ")
    self.wd.find_element(By.NAME, "group_footer").send_keys("sjdcnsd kcj sdkjc sjd c")
    # submit group creation
    self.wd.find_element(By.NAME, "submit").click()

  def open_groups_page(self):
    self.wd.find_element(By.LINK_TEXT, "groups").click()

  def login(self):
    self.wd.find_element(By.NAME, "user").send_keys("admin")
    self.wd.find_element(By.NAME, "pass").send_keys("secret")
    # self.wd.find_element(By.NAME, "pass").send_keys(Keys.ENTER) - doesn't work that way
    self.wd.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

  def open_home_page(self):
    self.wd.get("http://192.168.64.2/addressbook/index.php")
    self.wd.set_window_size(550, 691)
  
