# Generated by Selenium IDE
from model.group import Group


def test_add_group(app):
    app.group.create(Group(name="skdncjdns", header="kjndc skdjc ", footer="sjdcnsd kcj sdkjc sjd c"))


def test_add_empty_group(app):
    app.group.create(Group(name="", header="", footer=""))
